services:
  - type: web
    name: evnts-socket
    env: node
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGIN
        value: "*"
